name: Node.js CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    environment: testing

    steps:  
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '24.13.0'  # Specify your Node.js version

    - name: Install dependencies
      run: |
        cd webapp
        npm install   

    - name: Build application
      run: |
        cd webapp
        npm run build
